[package]
name = "linguist-chat-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
linguist-core.workspace = true
serde_json.workspace = true
ct2rs = { version = "=0.10.1", default-features = false, features = ["ruy", "sentencepiece"] }
whatlang = "=0.18.0"
isolang = "=2.4.0"
